[build]
  command = "npm run build:fe"
  publish = "dist/packages/ui-app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_APP_NAME = "What is the name of your app?"
  NEXT_PUBLIC_BE_GATEWAY = "What is the backend gateway URL?"

[context.production]
  environment = { }

[context.deploy-preview]
  environment = { }
